server:
  port: 8090

spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: airline

# actuator endpoint configurations
management:
  endpoint:
    health:
      show-details: always

logging.level.org.springframework.data.mongodb: DEBUG
logging.level.org.springframework.boot.autoconfigure: ERROR